name: walking_game
description: A GPS based walking game with map
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_compass: ^0.8.0
  pedometer: ^4.0.1
  intl: ^0.19.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
